POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTI5MjU5MzUsInN1YiI6ImU2NjFhZGI3LWMwZmEtNDQ3YS1hOWFjLTY2ZjcyMDA1ODMzOCJ9.KXjWXUnr4c-XolzsA8ms2jYMtLxXK7b_F6reaKBtUhY

###

GET http://localhost:8000/products/b6a6827e-ef5c-4dc3-bae2-35a61a38ef00 HTTP/1.1

###

PUT http://localhost:8000/products/b6a6827e-ef5c-4dc3-bae2-35a61a38ef00 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 101
}

###

DELETE http://localhost:8000/products/b6a6827e-ef5c-4dc3-bae2-35a61a38ef00 HTTP/1.1
